FROM docker.io/pgsty/mc@sha256:cfc83108c3abb371f8fb84d99c1fdc88f8c237e022409b0081fb7c0a3be634dd
LABEL org.opencontainers.image.source="https://github.com/Noveum/orbit"
COPY deploy/docker/initialize-storage.sh /initialize-storage.sh
ENTRYPOINT ["/bin/sh", "/initialize-storage.sh"]
